INSERT INTO series () VALUES ();
INSERT INTO series () VALUES ();

INSERT INTO () VALUES ();
INSERT INTO () VALUES ();

INSERT INTO () VALUES ();
INSERT INTO () VALUES ();

INSERT INTO () VALUES ();
INSERT INTO () VALUES ();
INSERT INTO () VALUES ();

INSERT INTO () VALUES ();
INSERT INTO () VALUES ();
INSERT INTO () VALUES ();

INSERT INTO () VALUES ();
INSERT INTO () VALUES ();
INSERT INTO () VALUES ();
INSERT INTO () VALUES ();
INSERT INTO () VALUES ();
INSERT INTO () VALUES ();
INSERT INTO () VALUES ();
INSERT INTO () VALUES ();